// Copies the browser libraries, fonts and the icon subset from node_modules into public/, so they are
// served as ordinary static files (locally by Express, and on Vercel as part of the deployed public/ folder).
// Runs automatically after `npm install` (postinstall). Run `npm run vendor` after upgrading these packages.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const nm = (p) => path.join(root, 'node_modules', p);
const out = (p) => path.join(root, 'public', p);

// Lucide icons used by public/app.js and public/index.html.
const UI_ICONS = [
  'ArrowUp', 'Square', 'RefreshCw', 'Plus', 'Copy', 'Check', 'ChevronDown', 'ChevronRight', 'Sparkles', 'Sun', 'Moon', 'Monitor',
  'PanelLeft', 'X', 'Receipt', 'ChartLine', 'ArrowUpDown', 'Scale', 'Landmark', 'CalendarDays', 'Target', 'ShieldCheck',
  'FileSpreadsheet', 'FileText', 'TriangleAlert', 'OctagonAlert', 'Info', 'Wallet', 'Clock', 'Building2', 'Workflow',
  'TrendingUp', 'TrendingDown', 'Coins', 'Gauge', 'Lightbulb', 'LayoutDashboard', 'Database', 'CircleCheck', 'Table2',
  'LoaderCircle', 'Minus',
];

const copies = [
  ['marked/lib/marked.umd.js', 'vendor/marked.js'],
  ['dompurify/dist/purify.min.js', 'vendor/purify.js'],
  ['geist/dist/fonts/geist-sans/Geist-Variable.woff2', 'fonts/geist-sans.woff2'],
  ['geist/dist/fonts/geist-mono/GeistMono-Variable.woff2', 'fonts/geist-mono.woff2'],
];

for (const dir of ['vendor', 'fonts']) fs.mkdirSync(out(dir), { recursive: true });
for (const [from, to] of copies) {
  fs.copyFileSync(nm(from), out(to));
  console.log(`vendor: ${to} (${fs.statSync(out(to)).size} bytes)`);
}

const { icons } = require('lucide');
const missing = UI_ICONS.filter((n) => !icons[n]);
if (missing.length) throw new Error(`Unknown Lucide icons: ${missing.join(', ')}`);
const subset = Object.fromEntries(UI_ICONS.map((n) => [n, icons[n]]));
fs.writeFileSync(out('vendor/icons.js'), `// Generated by scripts/copy-vendor.js (Lucide, ISC licence)\nwindow.ICONS=${JSON.stringify(subset)};\n`);
console.log(`vendor: vendor/icons.js (${UI_ICONS.length} icons)`);
